### ISSUE TITLE
Content within breakpoint statements only displays after refreshing

### ISSUE THREAD

**Issue by paulgodard** [TinaHammar/laravel-window-size#4]
When I open a page with the code below for the first time or when I change the window size on a desktop, the content within the correct breakpopint does not show unless I refresh the page. How can I make sure that refresh is automatic?

You can see it in action [in one of my blog](https://www.paulgodard.com/blog/79?title=Angolan_adventure).

Here is the code.

 <head>
 <x-window-size::save-to-session />
 </head>
 <body>
 @windowWidthGreaterThan(768)
 
 <div class="article-body d-none d-md-block">
    {!! $article->body !!}
 </div>
 @else
 
 <div class="article-body d-md-none">
    {!! $article->bodyX !!}
 </div>
 @endif
 </body>

**Comment by tanthammar** [comment]
As it says in the Readme file, there is a difference between this package and normal Css media queries. 
It doesn't update until the next network request.


The thought of this package is not to change the layout of the document when resizing the window, it is based on the assumption that a user arrives at the site with a device that keeps the same screen size during it's session.


Like, if you surf on a mobile or a tablet, you'll probably stay in that display size during your visit.


(It is mostly designers or developers who keep resizing the window to see what happens...)

My use case is only to serve a mobile version of the site that is much more light weight than the desktop version.

For me it is enough to know the window size on each network request.

I decided when I created the package that I didn't want to send a network requests in realtime.

Please see the readme, where this is described.

:)
